//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Book
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> subscribe { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
